// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// // from firebase step by-step guide
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
// //

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg6l9Fx92pFEO9a4H1lW6R84_GhEJpUoM',
    appId: '1:810381943500:web:a648ea624e1cebc6671869',
    messagingSenderId: '810381943500',
    projectId: 'whatsapp-clone-flutter-ff1fd',
    authDomain: 'whatsapp-clone-flutter-ff1fd.firebaseapp.com',
    storageBucket: 'whatsapp-clone-flutter-ff1fd.firebasestorage.app',
    measurementId: 'G-2H2V3LW7D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1yDuI9NC38ofdtfVW5tzQZiQQjlZIHc',
    appId: '1:810381943500:android:07ca9d1b18d0e8b0671869',
    messagingSenderId: '810381943500',
    projectId: 'whatsapp-clone-flutter-ff1fd',
    storageBucket: 'whatsapp-clone-flutter-ff1fd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg6l9Fx92pFEO9a4H1lW6R84_GhEJpUoM',
    appId: '1:810381943500:web:953715f2d971ac61671869',
    messagingSenderId: '810381943500',
    projectId: 'whatsapp-clone-flutter-ff1fd',
    authDomain: 'whatsapp-clone-flutter-ff1fd.firebaseapp.com',
    storageBucket: 'whatsapp-clone-flutter-ff1fd.firebasestorage.app',
    measurementId: 'G-WCM5RDSBJ8',
  );
}
